version: '3.8'
services:
  postgres:
    image: postgres:14-alpine3.15
    container_name: clancy-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data/:/var/lib/postgresql/data/
    networks:
      - clancy
  middleware:
    build: .
    image: clancy-middleware
    container_name: clancy-middleware
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: 3000
    volumes:  
      - ./logs/:/usr/src/app/logs
      - ./locale:/usr/src/locale
      - ./logs/unhandled.log:/usr/src/app/logs/unhandled.log
    networks:
      - clancy

volumes:
  db-data:
  
networks:
  clancy:
    driver: bridge
    name: clancy
